version: "3.8"

services:
  db:
    image: postgres:17.4-alpine3.21
    container_name: PaperlessDB
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 2s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - paperless-network

  minio:
    image: minio/minio
    container_name: MinIO
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - paperless-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: RabbitMQ
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management UI
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping && nc -z localhost 5672"]
      interval: 5s
      retries: 5
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - paperless-network

  ocrworker:
    build:
      context: .
      dockerfile: ./PaperlessServices/OcrWorker/Dockerfile
    container_name: OcrWorker
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - paperless-network

  api:
    build:
      context: .
      dockerfile: ./PaperlessREST/Dockerfile
    container_name: PaperlessREST
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_URLS: "http://+:5000"
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
      MINIO_ENDPOINT: ${MINIO_HOST}:9000
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - paperless-network

  web:
    build:
      context: ./PaperlessWebUI
      dockerfile: Dockerfile
    container_name: PaperlessWebUI
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - paperless-network

networks:
  paperless-network:
    driver: bridge

volumes:
  postgres_data:
  minio_data:
  rabbitmq_data:
